name: Java CI with Maven

on: [pull_request, push]

jobs:
  install:
    - name: Instalando packages
      runs-on: ubuntu-latest
      steps:
      # Dar acesso da máquina virtual ao projeto
        - name: Checkout
        - uses: actions/checkout@v3
        
        - name: cache node_modules
        - uses: actions/cache@v2
          with:
            path: node_modules
            key
            
        - name: Instalando dependencias
        - uses: npm install
  
  testing:
    - name: Testando
      run: npm test
